SELECT DISTINCT c.CAR_ID
FROM  CAR_RENTAL_COMPANY_CAR c
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY r ON c.CAR_ID = r.CAR_ID
WHERE DATE_FORMAT(r.START_DATE, '%m') = '10' AND c.CAR_TYPE = '세단'
ORDER BY c.CAR_ID DESC