SELECT MONTH(r.START_DATE) AS MONTH, r.CAR_ID, COUNT(r.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY r
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
) AS filtered_cars ON r.CAR_ID = filtered_cars.CAR_ID
WHERE DATE_FORMAT(r.START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH(r.START_DATE), r.CAR_ID
HAVING COUNT(r.HISTORY_ID) > 0
ORDER BY MONTH ASC, r.CAR_ID DESC;