SELECT f.CATEGORY, f.PRICE AS 'MAX_PRICE', f.PRODUCT_NAME
FROM FOOD_PRODUCT f
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS "PRICE"
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) j ON (f.CATEGORY = j.CATEGORY AND f.PRICE = j.PRICE) 
WHERE f.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC